version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "passenger-trip"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2zk3jncixruc"
s3_prefix = "passenger-trip"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
